# Generated by Django 6.0.5 on 2026-05-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
