# Generated by Django 6.0.5 on 2026-05-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortapp', '0002_shorturl_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
