# Generated by Django 6.0.5 on 2026-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('lesson_type', models.CharField(blank=True, choices=[('theory', 'Теория'), ('practice', 'Практика'), ('live', 'Онлайн')], default='theory', verbose_name='Тип урока')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('position',),
            },
        ),
    ]
