# Generated by Django 6.0.5 on 2026-05-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='lesson_materials/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Материал урока',
                'verbose_name_plural': 'Материалы уроков',
            },
        ),
    ]
