# Generated by Django 6.0.5 on 2026-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmaterial',
            name='material_type',
            field=models.CharField(choices=[('file', 'Файл'), ('link', 'Ссылка')], default='file', max_length=10, verbose_name='Тип материала'),
        ),
    ]
