# Generated by Django 6.0.5 on 2026-06-23 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessonmaterial_material_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=1, verbose_name='Длительность в минутах'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/image', verbose_name='Превью урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
    ]
