# Generated by Django 6.0.5 on 2026-06-23 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_duration_minutes_lesson_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Видео')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Видео урока',
                'verbose_name_plural': 'Видео уроков',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='LessonVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position_seconds', models.PositiveIntegerField(default=0, verbose_name='Последняя позиция в секундах')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Длительность в секундах')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_video_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lessons.lessonvideo', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Прогресс просмотра видео урока',
                'verbose_name_plural': 'Прогресс просмотра видео уроков',
                'ordering': ('updated_at',),
            },
        ),
    ]
