# Generated by Django 6.0.5 on 2026-06-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lessonvideo_lessonvideoprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmaterial',
            name='material_type',
            field=models.CharField(choices=[('file', 'pdf'), ('link', 'Ссылка'), ('doc', 'docx')], default='file', max_length=10, verbose_name='Тип материала'),
        ),
    ]
