# Generated by Django 6.0.5 on 2026-06-30 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lessonmaterial_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('passing_score', models.PositiveIntegerField(default=1, verbose_name='Проходной балл')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Тест урока',
                'verbose_name_plural': 'Тесты уроков',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons.lessontest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lessons.testquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ теста',
                'verbose_name_plural': 'Ответы теста',
                'ordering': ('position',),
            },
        ),
    ]
